bot_token: 1234567890:ABCDEFGHIJKLMNOUPRSTUWXYZ123456789100

database_settings:
  provider: postgres
  user: inpost
  password: password
  host: 127.0.0.1
  database: inpost

telethon_settings:
  session: InpostBot
  auto_reconnect: true
  retry_delay: 15
  connection_retries: -1
  request_retries: 5

  api_id: 1234567
  api_hash: ABCDEFGHIJKLMNOUPRSTUWXYZ1234567

log_level: DEBUG